# Generated by Django 3.2.15 on 2026-01-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_task_id_to_projectstage'),
        ('projects', '0002_project_jianying_draft_path'),
    ]

    operations = [
    ]
