# Generated by Django 3.2.15 on 2026-01-13 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_merge_20260112_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_data', models.JSONField(verbose_name='工作流数据')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '运行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('current_node_id', models.CharField(blank=True, max_length=100, verbose_name='当前节点ID')),
                ('execution_results', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目工作流',
                'verbose_name_plural': '项目工作流',
                'db_table': 'project_workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(max_length=50, unique=True, verbose_name='节点类型')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('category', models.CharField(choices=[('input', '输入'), ('processing', '处理'), ('ai', 'AI生成'), ('output', '输出'), ('control', '控制')], max_length=20, verbose_name='分类')),
                ('config_schema', models.JSONField(verbose_name='配置模式')),
                ('input_ports', models.JSONField(default=list, verbose_name='输入端口')),
                ('output_ports', models.JSONField(default=list, verbose_name='输出端口')),
                ('processor_class', models.CharField(max_length=255, verbose_name='处理器类')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='颜色')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('help_text', models.TextField(blank=True, verbose_name='帮助文本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作流节点',
                'verbose_name_plural': '工作流节点',
                'db_table': 'workflow_nodes',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('workflow_data', models.JSONField(verbose_name='工作流数据')),
                ('preview_image', models.CharField(blank=True, max_length=512, verbose_name='预览图')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '工作流模板',
                'verbose_name_plural': '工作流模板',
                'db_table': 'workflow_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('logs', models.JSONField(blank=True, default=list, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='projects.projectworkflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '工作流执行记录',
                'verbose_name_plural': '工作流执行记录',
                'db_table': 'workflow_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.workflowtemplate', verbose_name='基于模板'),
        ),
    ]
