# Generated by Django 3.2.15 on 2026-01-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20260113_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundMusic',
        ),
        migrations.DeleteModel(
            name='TransitionEffect',
        ),
        migrations.DeleteModel(
            name='VideoFilter',
        ),
        migrations.AlterField(
            model_name='video',
            name='generation_type',
            field=models.CharField(choices=[('text_to_video', '文本转视频'), ('image_to_video', '图片转视频'), ('storyboard_to_video', '故事板转视频'), ('story_to_video', '故事转视频'), ('drama', '短剧制作'), ('anime', '动漫制作'), ('comic', '漫画制作')], max_length=50, verbose_name='生成类型'),
        ),
    ]
